version: '3.7'

services:
  db:
    container_name: 'postgres'
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
  admin:
    container_name: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

volumes:
  db:
    driver: local
networks:
  app_network:
    external: true
